#!/bin/bash

echo "Chrome 139 Installation Script"
echo "==============================="
echo ""
echo "Note: You already have Chromium 139 installed which works with the code."
echo "If you still want to install Chrome 139, follow these steps:"
echo ""
echo "1. Remove current Chrome 140:"
echo "   sudo apt remove google-chrome-stable -y"
echo ""
echo "2. Download Chrome 139 manually from:"
echo "   https://www.slimjet.com/chrome/google-chrome-old-version.php"
echo "   Look for version 139.0.6903.60"
echo ""
echo "3. Install the downloaded .deb file:"
echo "   sudo dpkg -i google-chrome-stable_139*.deb"
echo "   sudo apt-get install -f  # Fix any dependency issues"
echo ""
echo "4. Prevent auto-update:"
echo "   sudo apt-mark hold google-chrome-stable"
echo ""
echo "Alternative: Use Chromium (already installed):"
echo "   The code has been updated to use Chromium 139 at /snap/bin/chromium"